### ISSUE TITLE
Error While loading file 'O_level_frame.tscn' 

### ISSUE THREAD

**Issue by Ryunoshi-source** [ChloePrime/MarioForeverMoleEditor#1]

**Comment by ChloePrime** [comment]
Any more info?

**Comment by Ryunoshi-source** [comment]
I got a popup after opening the project saying: Error While loading file 'O_level_frame.tscn' 
it also happens when trying to load any other scene (example.tscn,O_mario.tscn...etc)
Godot version : v4.1.1 mono

**Comment by ChloePrime** [comment]
Can't reproduce, try delete `.godot` folder and reimport, or reclone this repository

**Comment by ChloePrime** [comment]
btw this project uses .net 7, .net6 won't compile

**Comment by Ryunoshi-source** [comment]
yes I did have .net6 installed before so uninstalled it , and i installed .net 7 both 64bit and 32bit versions but the it doesn't seem like thats whats causing the issue 
![image](https://github.com/ChloePrime/MarioForeverMoleEditor/assets/96547485/9ff79c34-e95e-4685-80b7-dbdaf3266963)

I Deleted the project folder and reimported it again and still got the same error :
https://github.com/ChloePrime/MarioForeverMoleEditor/assets/96547485/161981d2-a92f-4ab9-90a3-65139338046e

**Comment by Ryunoshi-source** [comment]
**I Finally found the Fix:**
After cloning your repository with **Git Bash** it worked just fine!
It seems like downloading it as a zip file causes the issue .

**Comment by ChloePrime** [comment]
Congratulations!
